apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-api-deployment
  labels:
    app: booking-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-api
  template:
    metadata:
      labels:
        app: booking-api
    spec:
      containers:
        - name: booking-api
          image: o-teu-usuario-dockerhub/booking-api:latest # Substitui pelo teu repositório futuramente
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: "postgres-service" # Exemplo de como a API encontraria o banco no K8s
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"